const fs = require('fs');
const path = require('path');
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');

/**
 * Turns off every automatic copy of this app's data.
 *
 * Aarogya holds prescriptions, lab values and a medication history for a named person.
 * Android's default is to back all of that up to the user's Google Drive and to hand it
 * to any new phone during device-to-device transfer, encrypted with a key the user
 * cannot see and did not choose. That is a reasonable default for a game and the wrong
 * one for a health record, so all three switches go off:
 *
 *   allowBackup=false        the legacy (pre-31) full-backup path
 *   fullBackupContent=false  the legacy auto-backup ruleset
 *   dataExtractionRules      the Android 12+ replacement, excluding everything
 *
 * The last one is a resource, not an attribute, so it is written to disk here. Setting
 * only the first two leaves Android 12+ devices backing everything up as before.
 */

const RES_FILE = 'aarogya_data_extraction_rules.xml';
const MARKER = '@generated by plugins/withNoBackup.js';

const EXCLUDES = [
  'root',
  'file',
  'database',
  'sharedpref',
  'external',
  'device_root',
  'device_file',
  'device_database',
  'device_sharedpref',
];

function rulesXml() {
  const excludes = EXCLUDES.map((d) => `        <exclude domain="${d}" />`).join('\n');
  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  ${MARKER} — DO NOT EDIT BY HAND.

  Every domain is excluded from both paths. <cloud-backup> covers Google Drive backup;
  <device-transfer> covers the phone-to-phone copy during setup, which is a SEPARATE
  opt-out — excluding one and not the other is the classic half-fix.
-->
<data-extraction-rules>
    <cloud-backup>
${excludes}
    </cloud-backup>
    <device-transfer>
${excludes}
    </device-transfer>
</data-extraction-rules>
`;
}

const withDataExtractionRulesFile = (config) =>
  withDangerousMod(config, [
    'android',
    (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml'
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      const target = path.join(xmlDir, RES_FILE);

      // Always rewritten rather than skipped-if-present: this file is generated output
      // living inside a generated directory, and a stale copy from an older version of
      // this plugin would be invisible and wrong.
      fs.writeFileSync(target, rulesXml(), 'utf8');
      return cfg;
    },
  ]);

const withManifestFlags = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application && cfg.modResults.manifest.application[0];
    if (!application) {
      // Hard throw, never a silent no-op. A silent skip here ships an app that quietly
      // uploads a family's medical history to a cloud account — and nothing in the build,
      // the app, or the device ever says so.
      throw new Error(
        '[withNoBackup] no <application> node in AndroidManifest.xml. Refusing to ' +
          'continue: without these attributes the health database is backed up to Google ' +
          'Drive and copied during device transfer, silently.'
      );
    }

    application.$['android:allowBackup'] = 'false';
    application.$['android:fullBackupContent'] = 'false';
    application.$['android:dataExtractionRules'] = `@xml/${RES_FILE.replace(/\.xml$/, '')}`;

    return cfg;
  });

const withNoBackup = (config) => withManifestFlags(withDataExtractionRulesFile(config));

module.exports = withNoBackup;
