const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Gradle settings that make a release build of this app finish at all.
 *
 * The metaspace number is the important one. Expo's template ships
 * `-XX:MaxMetaspaceSize=512m`, and R8 in full mode on a project this size (React Native,
 * Expo modules, expo-sqlite, the charting stack) loads enough classes to exhaust it. The
 * failure is not a clean OOM: the Gradle daemon dies mid-task and the build reports
 * "Daemon disappeared unexpectedly" or "Unable to find method", which sends you looking
 * at dependency conflicts for an afternoon. Both `enableMinifyInReleaseBuilds` and
 * `enableShrinkResourcesInReleaseBuilds` are on in app.config.ts, so this is not
 * hypothetical for this project.
 */

const MARKER = '@generated by plugins/withGradlePerformance.js';

const PROPERTIES = [
  {
    key: 'org.gradle.jvmargs',
    value: '-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8',
  },
  {
    key: 'org.gradle.parallel',
    value: 'true',
  },
];

function setProperty(items, key, value) {
  // Remove any existing declaration first. gradle.properties takes the LAST value for a
  // duplicated key, but leaving two lines that disagree is how a "fix" gets reverted six
  // months later by someone reading the first one.
  const filtered = items.filter((item) => !(item.type === 'property' && item.key === key));
  filtered.push({ type: 'property', key, value });
  return filtered;
}

const withGradlePerformance = (config) =>
  withGradleProperties(config, (cfg) => {
    let items = cfg.modResults;

    const alreadyMarked = items.some(
      (item) => item.type === 'comment' && String(item.value || '').includes(MARKER)
    );
    if (!alreadyMarked) {
      items.push({ type: 'comment', value: ` ${MARKER}` });
    }

    for (const { key, value } of PROPERTIES) {
      items = setProperty(items, key, value);
    }

    cfg.modResults = items;
    return cfg;
  });

module.exports = withGradlePerformance;
