const { withMainApplication } = require('@expo/config-plugins');

// THE single source of truth. Required, never re-declared: if this plugin carried its
// own copy of the channel table, the day someone edited one and not the other, a
// medicine would start ringing on a channel whose properties nobody chose.
const {
  CHANNELS,
  USAGE_ALARM,
} = require('../src/constants/channels.js');

const MARKER = '// @generated by plugins/withNotificationChannels.js';
const ANCHOR = 'super.onCreate()';

/** Kotlin string literal. Escapes backslash, quote, and `$` (which interpolates). */
function kt(str) {
  return `"${String(str)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\$/g, '\\$')
    .replace(/\r?\n/g, '\\n')}"`;
}

function channelKotlin(c, indent) {
  const i = indent;
  const isAlarm = c.usage === USAGE_ALARM;
  const defaultRingtoneType = isAlarm
    ? 'android.media.RingtoneManager.TYPE_ALARM'
    : 'android.media.RingtoneManager.TYPE_NOTIFICATION';

  const lines = [];
  lines.push(`${i}// ${c.id} — ${c.name}`);
  // Created only when absent. Android ignores importance/sound changes on an existing
  // channel, so re-creating it would be a no-op that merely LOOKS like it configures
  // something. To change behaviour you bump the id (_v1 -> _v2) in channels.js.
  lines.push(`${i}if (nm.getNotificationChannel(${kt(c.id)}) == null) {`);
  lines.push(
    `${i}  val ch = android.app.NotificationChannel(${kt(c.id)}, ${kt(c.name)}, ${c.importance})`
  );
  lines.push(`${i}  ch.description = ${kt(c.description)}`);
  lines.push(`${i}  ch.lockscreenVisibility = ${c.visibility}`);

  if (c.lightColor) {
    lines.push(`${i}  ch.enableLights(true)`);
    lines.push(`${i}  ch.lightColor = android.graphics.Color.parseColor(${kt(c.lightColor)})`);
  } else {
    lines.push(`${i}  ch.enableLights(false)`);
  }

  if (Array.isArray(c.vibration) && c.vibration.length > 0) {
    const pattern = c.vibration.map((n) => `${Number(n)}L`).join(', ');
    lines.push(`${i}  ch.enableVibration(true)`);
    lines.push(`${i}  ch.vibrationPattern = longArrayOf(${pattern})`);
  } else {
    lines.push(`${i}  ch.enableVibration(false)`);
  }

  // Belt and braces. setBypassDnd only takes effect if the app holds notification policy
  // access, which we never ask for; the real DND exemption comes from USAGE_ALARM, which
  // ZenModeFiltering.isAlarm() matches on. Harmless when ignored.
  lines.push(`${i}  ch.setBypassDnd(${c.bypassDnd ? 'true' : 'false'})`);

  // The audio attributes are the load-bearing part. USAGE_ALARM maps to STREAM_ALARM,
  // which ringer-silent never zeroes, which is why a dose sounds on a silenced phone.
  lines.push(`${i}  val attrs = android.media.AudioAttributes.Builder()`);
  lines.push(`${i}    .setUsage(${c.usage})`);
  lines.push(`${i}    .setContentType(${c.contentType})`);
  lines.push(`${i}    .build()`);

  if (c.sound) {
    // Resolved by name at runtime rather than by R.raw.<id> at compile time: if the audio
    // file has not been added to the project yet, a compile-time reference fails the
    // build, while a missing runtime lookup falls back to the system alarm tone and the
    // reminder still rings. Wrong tone beats no reminder.
    lines.push(`${i}  val soundId = resources.getIdentifier(${kt(c.sound)}, "raw", packageName)`);
    lines.push(`${i}  val sound = if (soundId != 0)`);
    lines.push(
      `${i}    android.net.Uri.parse("android.resource://" + packageName + "/" + soundId)`
    );
    lines.push(`${i}  else`);
    lines.push(`${i}    android.media.RingtoneManager.getDefaultUri(${defaultRingtoneType})`);
    lines.push(`${i}  ch.setSound(sound, attrs)`);
  } else {
    lines.push(
      `${i}  ch.setSound(android.media.RingtoneManager.getDefaultUri(${defaultRingtoneType}), attrs)`
    );
  }

  lines.push(`${i}  nm.createNotificationChannel(ch)`);
  lines.push(`${i}}`);
  return lines.join('\n');
}

function buildBlock() {
  const i = '    ';
  const body = CHANNELS.map((c) => channelKotlin(c, `${i}  `)).join('\n\n');
  return [
    '',
    `${i}${MARKER} — DO NOT EDIT BY HAND.`,
    `${i}// Channels are created HERE, in Application.onCreate(), and not from JS.`,
    `${i}// A dose alarm starts this process with no Activity and no React tree; if the`,
    `${i}// channel did not already exist at that moment, the notification would be`,
    `${i}// dropped by the system with nothing but a logcat line to show for it.`,
    `${i}// Generated from src/constants/channels.js — edit that file, then re-run prebuild.`,
    `${i}run {`,
    `${i}  val nm = getSystemService(android.content.Context.NOTIFICATION_SERVICE)`,
    `${i}    as android.app.NotificationManager`,
    '',
    body,
    `${i}}`,
    '',
  ].join('\n');
}

/**
 * Injects notification-channel creation into MainApplication.onCreate().
 */
const withNotificationChannels = (config) =>
  withMainApplication(config, (cfg) => {
    const { language } = cfg.modResults;
    if (language !== 'kt') {
      throw new Error(
        `[withNotificationChannels] expected a Kotlin MainApplication, got "${language}". ` +
          'Expo SDK 54 generates MainApplication.kt; a Java one means the template changed ' +
          'and this plugin must be updated rather than silently skipped.'
      );
    }

    // Idempotency. prebuild can run this twice in one pass, and a second injection would
    // create every channel twice (harmless) and make the file impossible to read (not).
    if (cfg.modResults.contents.includes(MARKER)) {
      return cfg;
    }

    const anchorIndex = cfg.modResults.contents.indexOf(ANCHOR);
    if (anchorIndex === -1) {
      // HARD THROW, never a silent no-op. A no-op here ships an APK whose five channels
      // do not exist, so every reminder is swallowed by the system — and it looks
      // completely fine at build time. `prebuild --clean` regenerates MainApplication,
      // so this failure mode is one template change away at all times.
      throw new Error(
        `[withNotificationChannels] anchor "${ANCHOR}" not found in MainApplication.kt. ` +
          'Refusing to continue: without this injection the app builds successfully and ' +
          'then silently delivers no reminders at all.'
      );
    }

    const insertAt = anchorIndex + ANCHOR.length;
    cfg.modResults.contents =
      cfg.modResults.contents.slice(0, insertAt) +
      '\n' +
      buildBlock() +
      cfg.modResults.contents.slice(insertAt);

    return cfg;
  });

module.exports = withNotificationChannels;
